Avoid adding integers to strings
libreswan/libreswan pull request #395
Opened 2021-01-12 06:57 UTC by tbaederr

Although a common C idiom, clang warns about this:

lib/libswan/jam_nss_ckf.c:36:2: error: adding 'unsigned long' to a string does not append to the string [-Werror,-Wstring-plus-int]
        FLAG(CKF_SIGN);
        ^~~~~~~~~~~~~~
lib/libswan/jam_nss_ckf.c:32:30: note: expanded from macro 'FLAG'
                size += jam_string(buf, #F + strlen("CKF_"));   \
                                        ~~~^~~~~~~~~~~~~~~~

Fix this by using an array index instead.

2021-01-13 15:18 UTC, cagney requested changes
Can some sort of brief comment hinting why the strange expression is being used be added to each change.  Even:
  clang's -Wstring-plus-int errors: "cka_string"+strlen("cka_")
It will hopefully reduce the odds of a cleanup reverting the change, and encourage any one copying the code to use the same workaround.

Otherwise good-to-go

2021-01-14 13:09 UTC, tbaederr commented
Added an explanation to each change.

2021-01-15 01:08 UTC, cagney commented
Nice.
Paul, can you merge please.

2021-01-15 17:59 UTC, closed without merging

2021-02-23 20:38 UTC, HughR commented
For C code, this is a stupid warning.  For history:

<https://reviews.llvm.org/rGccec40d9b75602c35025140fff5c4cdbd5f99f8d>

I just added a comment asking that it be not used with C.  I'm not holding 
my breath.

| From: tbaederr <notifications@github.com>
| To: libreswan/libreswan <libreswan@noreply.github.com>
| Cc: Subscribed <subscribed@noreply.github.com>
| Date: Mon, 11 Jan 2021 22:57:18 -0800
| Subject: [libreswan/libreswan] Avoid adding integers to strings (#395)
| Reply-To: libreswan/libreswan
|     <reply@reply.github.com>
| 
| Although a common C idiom, clang warns about this:
| 
| lib/libswan/jam_nss_ckf.c:36:2: error: adding &#39;unsigned long&#39; to a string does not append to the string [-Werror,-Wstring-plus-int]
|         FLAG(CKF_SIGN);
|         ^~~~~~~~~~~~~~
| lib/libswan/jam_nss_ckf.c:32:30: note: expanded from macro &#39;FLAG&#39;
|                 size += jam_string(buf, #F + strlen(&quot;CKF_&quot;));   \
|                                         ~~~^~~~~~~~~~~~~~~~
| 
| Fix this by using an array index instead.
| You can view, comment on, or merge this pull request online at:
| 
|   https://github.com/libreswan/libreswan/pull/395
| 
| -- Commit Summary --
| 
|   * Avoid adding integers to strings
| 
| -- File Changes --
| 
|     M lib/libswan/jam_nss_cka.c (2)
|     M lib/libswan/jam_nss_ckf.c (2)
|     M lib/libswan/jam_nss_ckm.c (2)
|     M programs/pluto/ikev1_states.c (2)
|     M programs/pluto/ikev2_states.c (4)
| 
| -- Patch Links --
| 
| https://github.com/libreswan/libreswan/pull/395.patch
| https://github.com/libreswan/libreswan/pull/395.diff
| 
| -- 
| You are receiving this because you are subscribed to this thread.
| Reply to this email directly or view it on GitHub:
| https://github.com/libreswan/libreswan/pull/395
|